### ISSUE TITLE
Error: source file could not be loaded

### ISSUE THREAD

**Issue by budingts** [ipunkt/docker-libreoffice-headless#1]
the host has  /tmp/aa.pptx

when i run 

`docker run --rm -it -v /tmp:/tmp --name libreoffice-headless ipunktbs/docker-libreoffice-headless --convert-to pdf  –outdir /tmp  /tmp/aa.pptx`

show the error

`W: Unknown node under /registry/extlang: deprecated
W: Unknown node under /registry/grandfathered: comments
W: Unknown node under /registry/grandfathered: comments
W: Unknown node under /registry/extlang: deprecated
W: Unknown node under /registry/grandfathered: comments
W: Unknown node under /registry/grandfathered: comments
Error: source file could not be loaded`

**Comment by crapthings** [comment]
ubuntu 16.04

same here.28|cube-of | Error: W: Unknown node under /registry/extlang: deprecated
28|cube-of | W: Unknown node under /registry/grandfathered: comments
28|cube-of | W: Unknown node under /registry/grandfathered: comments

unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
LibreOffice 5.4.4.2

**Comment by rokde** [comment]
the `convert.sh` shows an example usage with mounting only the local `.` directory. You have to mount your local directory the same way.

**Comment by josx** [comment]
same problem, i cant use it with convert.sh either

**Comment by rokde** [comment]
We do not maintain this repo anymore. Please fork and change it to your needs.
