### ISSUE TITLE
Consider upgrading to Ubuntu 18.04

### ISSUE THREAD

**Issue by beruic** [ipunkt/docker-libreoffice-headless#3]
New LTS is out with a newer version of LibreOffice.
Upgrading is inevitable in the long run.

**Comment by justb81** [comment]
A PR would be really appreciated.

**Comment by beruic** [comment]
Sorry, I  just noticed the use of the older LTS version, an wanted to give a friendly reminder.
I'm still in the phase of trying to figure out whether this is the right approach for my project, and how to apply it, if so :)

**Comment by beruic** [comment]
Well... I made a pull request anyway :)

**Comment by justb81** [comment]
@rokde could you check the updated version?

**Comment by rokde** [comment]
Merge upgrades to Ubuntu 18.04
